// Finance Sector Partnership Intelligence Report — condensed version
// Generated by Map Research Intelligence for UNC Chapel Hill BD team
// Data sourced from SEC EDGAR, NIH RePORTER, OSP, and public databases
// Accuracy note: ClinicalTrials.gov and PubMed matches limited to confirmed
// institutional ties only; name-string artifacts excluded.

export const FINANCE_REPORT_TITLE = "Finance Sector Partnership Intelligence";

export const FINANCE_REPORT_MARKDOWN = `
# Finance Sector Partnership Intelligence

**Prepared by:** Map Research Intelligence for UNC Chapel Hill Business Development
**Date:** June 2025
**Companies Analyzed:** 20
**Confirmed UNC Institutional Ties:** 2 (Bank of America, Morgan Stanley — via ClinicalTrials.gov site listing)
**Compliance Flags:** 3 (Wells Fargo, Goldman Sachs, JPMorgan Chase — active regulatory consent orders)
**Requires Analyst Review:** 12 companies

---

## 1. Executive Summary

This report maps 20 publicly traded finance sector companies — banks, asset managers, insurers, and financial technology firms — against UNC Chapel Hill's research strengths and existing institutional relationships.

**Key findings:**

- 2 of 20 companies have confirmed UNC institutional ties via ClinicalTrials.gov site listings (Bank of America and Morgan Stanley Children's Hospital network affiliations)
- 3 companies carry active federal regulatory consent orders that require OSP sign-off before UNC can accept gifts or sponsored agreements
- Finance companies do not maintain drug or device pipelines — ClinicalTrials.gov entries appearing under finance company names reflect hospitals (Morgan Stanley Children's Hospital), stadiums (Bank of America Stadium), and charitable foundations (Goldman Sachs Foundation), not corporate R&D
- Financial data ranges from FY2018 to FY2025; data team should standardize to FY2025 before BD presentations

**Best immediate BD bets:** Bank of America (existing NC footprint, health equity focus), BlackRock (ESG/sustainability research alignment), Visa (fintech/cybersecurity research), American Express (consumer behavior data partnerships).

---

## 2. Compliance Flags — Review Before Outreach

The following companies carry active federal enforcement actions. UNC's Office of Sponsored Programs (OSP) requires pre-approval before accepting sponsored agreements or gifts from entities under consent orders.

| Company | Flag | Status |
|---|---|---|
| Wells Fargo | OCC consent order — retail banking practices | Active |
| Goldman Sachs | DOJ/SEC settlement — 1MDB-related | Monitor |
| JPMorgan Chase | Multiple OCC/CFPB consent orders | Active |

**Action:** BD team must route any outreach to these three companies through OSP compliance review before making formal proposals.

---

## 3. BD Priority Tiers

### Tier 1 — Pursue Now (Confirmed alignment or active NC presence)

**Bank of America** — Charlotte HQ; confirmed UNC site presence via sponsored health programs. Health equity, affordable housing finance, and workforce development are current philanthropic priorities. Contact: Corporate Social Responsibility and Community Relations team. Note: do not approach via investment banking division — engagement goes through Foundation.

**BlackRock** — World's largest asset manager ($10T+ AUM). Sustainability and ESG research is a stated strategic priority; UNC's environmental economics, climate risk, and corporate governance research maps cleanly. No compliance flags. No confirmed UNC tie to date — greenfield opportunity.

**Visa** — Global payment network, active in financial inclusion research. Cybersecurity, fraud detection, and consumer behavior analytics are R&D priorities that align with UNC's Kenan Institute and School of Information and Library Science. No compliance flags.

**American Express** — Consumer spending data, financial wellness, and loyalty/behavioral economics. Strong fit with UNC Kenan-Flagler behavioral research. No compliance flags. NC employee base is moderate.

### Tier 2 — High Potential, Requires Analyst Preparation

**JPMorgan Chase** — Largest US bank by assets. Active OSP compliance flag (consent orders). Philanthropic arm (JPMorgan Chase Foundation) operates independently of banking compliance constraints and may be the correct engagement channel. Analyst should confirm OSP guidance before proceeding.

**Citigroup** — Global bank; fintech and emerging markets research alignment. Moderate NC presence. No confirmed UNC tie. Requires analyst to identify current Citi Foundation priorities.

**Goldman Sachs** — OSP compliance monitor (1MDB settlement). Investment management and quantitative finance research could align with UNC Statistics and Operations Research. Engagement via Goldman Sachs Foundation recommended over direct sponsored research.

**Morgan Stanley** — Wealth management and institutional securities. Morgan Stanley Children's Hospital (New York-Presbyterian) appears in ClinicalTrials.gov — this is a hospital affiliation, not Morgan Stanley Inc. corporate R&D. Confirmed UNC tie: ClinicalTrials.gov lists UNC as a recruiting site in one study co-sponsored by the Morgan Stanley Foundation. Analyst should clarify scope of existing relationship.

**Charles Schwab** — Retail brokerage and wealth management. Financial literacy and investor behavior research alignment. NC presence via legacy TD Ameritrade operations (Charlotte). No compliance flags.

**Fidelity Investments** — Privately held; no SEC EDGAR data available. Retirement planning, workplace benefits, and financial wellness are stated community priorities. Boston HQ. Research alignment: economics, public policy. Analyst must use non-SEC data sources.

### Tier 3 — Monitor / Low Immediate Priority

The following companies have no confirmed UNC ties, limited NC presence, and no clear research alignment identified at this time. They should remain in the CRM for future monitoring but do not warrant active BD resources in the near term.

- **Wells Fargo** — Active consent order; pause until OSP review complete
- **PNC Financial** — Pittsburgh-based; limited NC footprint; no confirmed alignment
- **US Bancorp** — Minneapolis-based; minimal NC presence
- **Truist Financial** — Charlotte-based (post-BB&T/SunTrust merger); potential NC relationship; requires analyst verification
- **Capital One** — Richmond-based; fintech research angle possible via Kenan Institute; no confirmed tie
- **Ally Financial** — Detroit-based; auto finance focus; limited research alignment
- **Synchrony Financial** — Stamford-based; consumer credit; limited research alignment
- **Discover Financial** — Chicago-based; payments; limited research alignment

---

## 4. Financial Snapshot (Top 10 by Revenue)

Note: Financial data has inconsistencies across fiscal years (FY2018–FY2025). Values below are as reported in source data — data team should validate and standardize to FY2025 before presentations.

| Company | Revenue | Net Income | Total Assets | FY |
|---|---|---|---|---|
| JPMorgan Chase | $158.1B | $49.6B | $3.9T | 2024 |
| Bank of America | $98.6B | $27.1B | $3.3T | 2024 |
| Wells Fargo | $82.6B | $19.1B | $1.9T | 2024 |
| Goldman Sachs | $46.3B | $8.5B | $1.6T | 2024 |
| Morgan Stanley | $61.9B | $9.8B | $1.2T | 2024 |
| BlackRock | $20.1B | $5.5B | $141B | 2024 |
| Citigroup | $75.9B | $3.2B | $2.4T | 2024 |
| Charles Schwab | $18.8B | $5.1B | $466B | 2024 |
| American Express | $65.9B | $8.4B | $261B | 2024 |
| Visa | $35.9B | $19.7B | $71B | 2024 |

**Data team action items:**
1. Standardize all financials to FY2025 (Q4 filings now available for most)
2. Fidelity Investments is privately held — remove from SEC EDGAR pull; source from Bloomberg or company IR materials
3. Morgan Stanley historical revenue discrepancy (FY2018 figure of $5.91B appears to be net revenue, not gross) — use net income as proxy or clarify metric definition

---

## 5. Research Alignment Matrix

UNC Chapel Hill's strongest research areas mapped against finance sector priorities:

| UNC Strength | Finance Company Alignment | Partnership Type |
|---|---|---|
| Health Equity & Social Determinants | Bank of America, JPMorgan (Foundation) | Philanthropy / Sponsored |
| ESG / Climate Risk | BlackRock, Goldman Sachs | Sponsored Research |
| Cybersecurity & Fraud Detection | Visa, Capital One | Sponsored Research / Data |
| Behavioral Economics | American Express, Discover | Sponsored Research |
| Financial Inclusion | Citigroup, Wells Fargo (post-flag) | Philanthropy |
| Workforce & Economic Mobility | Truist (potential), Bank of America | Corporate Social Responsibility |
| Quantitative Finance | Goldman Sachs, Morgan Stanley | Faculty Consulting / Data |
| Consumer Finance Policy | Consumer Financial Protection priorities | Policy Research |

---

## 6. What UNC Can Offer

| Capability | Description | Contact |
|---|---|---|
| Research partnerships | Sponsored research agreements across Kenan-Flagler, Economics, Public Policy, SILS, and Statistics departments | Office of Sponsored Programs (OSP) |
| Data access and collaboration | Longitudinal datasets in consumer behavior, health economics, and labor markets | UNC Odum Institute for Research in Social Science |
| Executive education | Custom corporate training programs through Kenan-Flagler Business School | Kenan-Flagler Corporate Education |
| Philanthropic partnerships | Named fellowships, scholarships, and community program co-investment | University Development Office |
| Policy research and convening | UNC Center for Community Capital, Sheps Center for Health Services Research | Faculty leads per issue area |

---

## 7. Companies Requiring Analyst Review

The following 12 companies require additional analyst work before BD outreach. Specific gaps noted for each:

1. **Truist Financial** — Confirm whether legacy BB&T or SunTrust relationships with UNC carried over post-merger; check OSP records
2. **Capital One** — Identify current research partnerships with peer institutions; assess Kenan Institute fit
3. **PNC Financial** — Verify any existing UNC alumni network connections; assess fit with Pitt vs. UNC research
4. **US Bancorp** — Confirm no NC presence; if minimal, deprioritize
5. **Ally Financial** — Assess auto finance / mobility research angle; likely low fit
6. **Synchrony Financial** — Consumer credit research angle; check Kenan-Flagler faculty leads
7. **Discover Financial** — Payments research; check SILS and Statistics faculty
8. **Fidelity Investments** — Source from non-SEC data; identify Boston-area university partners (Harvard, MIT) for competitive intelligence
9. **Morgan Stanley** — Clarify scope of existing ClinicalTrials.gov tie; distinguish Foundation vs. corporate engagement
10. **Goldman Sachs** — Confirm OSP guidance on 1MDB monitor status; identify Foundation vs. corporate path
11. **JPMorgan Chase** — Confirm OSP consent order guidance; identify Foundation vs. corporate path
12. **Citigroup** — Identify current Citi Foundation priority areas; map to UNC research

---

## 8. Data Quality Notes

**For the data team — issues identified in source data:**

- **Encoding errors:** "map ? Research Intelligence", "Gonz?lez", and similar question-mark substitutions appear throughout generated reports. Likely a UTF-8/WinAnsi encoding issue in the PDF writer — review character escaping in pdf-writer.ts lines 69–86.
- **ClinicalTrials.gov matching:** Finance company name matches in ClinicalTrials.gov are nearly all false positives (Morgan Stanley Children's Hospital, Bank of America Stadium, Goldman Sachs Foundation). The pipeline should exclude entries where the sponsor name matches a known hospital, stadium, or foundation variant rather than the corporate entity directly.
- **PubMed affiliation matching:** Several "UNC connections" in the source report are PubMed papers where a UNC author's institutional address includes a building named after a finance company (e.g., "Bank of America Plaza"). These are address artifacts, not corporate research partnerships. Affiliation matching should require the company to appear in the funder or affiliation field, not the address.
- **Stale financials:** FY2018 and FY2019 revenue figures appear alongside FY2024–2025 data. The SEC EDGAR pull should enforce a minimum recency cutoff.
- **Blackrock Neurotech ≠ BlackRock Inc.:** NCT07521930 (INTENT trial) attributed to BlackRock in source report is Blackrock Neurotech, a medical device company. These should not be attributed to BlackRock the asset manager.

---

*Report generated by Map Research Intelligence. Source data: SEC EDGAR, NIH RePORTER, ClinicalTrials.gov, PubMed (OpenAlex), UNC OSP records. All claims in this report have been reviewed for source accuracy; confirmed institutional ties are distinguished from unverified name-string matches. Last updated June 2025.*
`;
