import type { AccountProfile } from "./accountProfile";

/**
 * Accounts parsed from the UNC "Database load template — Industry company
 * 06012026" source. The template's columns were visually misaligned in the
 * source export, so each report link was matched to its company by the
 * filename in the SharePoint URL (not by row position). Fields the source left blank were
 * researched June 12, 2026 — public companies verified against SEC EDGAR
 * (FY2025 Form 10-K / latest filings), private and government entities against
 * official websites; see ACCOUNTS_DATA.md at the repo root for full citations.
 *
 * Report links are auth-gated UNC SharePoint URLs (sign-in required).
 */

// Shared SharePoint folder prefix for the "Link to report" PDFs.
const RPT =
  "https://adminliveunc.sharepoint.com/:b:/r/sites/UNCInnovateCarolinaIndustryPartnerships-ResearchAnalyticsIntelligence/Shared%20Documents/Partnership%20Inventory%20Profiles%20(due%20June%208)/";

// takes: a filename and its SharePoint share token
// does: assembles the full auth-gated report URL from the shared folder prefix
// returns: the complete "Link to report" URL string
function rpt(file: string, e: string): string {
  return `${RPT}${file}?csf=1&web=1&e=${e}`;
}

// takes: a partial AccountProfile (only the fields present in the source)
// does: fills every missing AccountProfile field with an empty string so the
//       table can render a complete, strictly-typed row for each account
// returns: a fully-populated AccountProfile
function row(p: Partial<AccountProfile>): AccountProfile {
  return {
    account: "",
    companyAliases: "",
    parentAccount: "",
    topIndustrySectorProfile: "",
    secondaryIndustrySectorProfile: "",
    description: "",
    website: "",
    companyStructure: "",
    ownership: "",
    streetAddress: "",
    city: "",
    state: "",
    zipCode: "",
    country: "",
    approximateEmployees: "",
    approximateRevenue: "",
    keyProducts: "",
    businessSplit: "",
    researchBy: "",
    dateOfResearch: "",
    resources: "",
    linkToReport: "",
    ...p,
  };
}

export const ACCOUNTS: AccountProfile[] = [
  row({
    account: "Amazon Web Services (AWS)",
    companyAliases: "AWS, Amazon Web Services, Inc.",
    parentAccount: "Amazon.com, Inc.",
    topIndustrySectorProfile: "Cloud Computing / Infrastructure as a Service",
    secondaryIndustrySectorProfile: "Artificial Intelligence & Data Services",
    description: "AWS is Amazon's cloud computing division, providing on-demand compute, storage, database, networking, and AI/ML services to businesses, governments, and developers worldwide. It is the world's largest cloud infrastructure provider and Amazon's primary profit engine.",
    website: "https://aws.amazon.com",
    companyStructure: "Operating segment/subsidiary of Amazon.com, Inc.",
    ownership: "Public via parent Amazon.com, Inc. (NASDAQ: AMZN)",
    streetAddress: "410 Terry Avenue North",
    city: "Seattle",
    state: "WA",
    zipCode: "98109",
    country: "United States",
    approximateEmployees: "Not separately disclosed (Amazon total: ~1,576,000 full- and part-time as of Dec 31, 2025, per 10-K)",
    approximateRevenue: "~$128,700 (AWS segment net sales, FY2025)",
    keyProducts: "Amazon EC2, Amazon S3, Amazon Bedrock, AWS Lambda, Amazon RDS",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025 (Amazon.com, Inc., fiscal year ended Dec 31, 2025, filed Feb 2026) \u2014 https://www.sec.gov/Archives/edgar/data/0001018724/000101872426000004/amzn-20251231.htm",
    linkToReport: rpt("Amazon_Web_Services_(AWS)_Partnership_Profile.pdf", "47XvoE"),
  }),
  row({
    account: "Anthropic",
    companyAliases: "Anthropic PBC, Anthropic, P.B.C.",
    topIndustrySectorProfile: "Artificial Intelligence",
    secondaryIndustrySectorProfile: "Enterprise Software / AI Safety Research",
    description: "Anthropic is an AI safety and research company that builds the Claude family of large language models and related developer APIs. It operates as a public benefit corporation focused on developing reliable, interpretable, and steerable AI systems.",
    website: "https://www.anthropic.com",
    companyStructure: "Public benefit corporation (Delaware PBC)",
    ownership: "Private (venture-backed; investors include Amazon and Google)",
    streetAddress: "548 Market Street",
    city: "San Francisco",
    state: "CA",
    zipCode: "94104",
    country: "United States",
    approximateEmployees: "Not disclosed (estimated 2,000+)",
    approximateRevenue: "Not disclosed",
    keyProducts: "Claude (LLM assistant), Claude API, Claude Code, Claude for Enterprise",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "https://www.anthropic.com (official website; company page https://www.anthropic.com/company)",
    linkToReport: rpt("Anthropic_Partnership_Profile.pdf", "vjBY3C"),
  }),
  row({
    account: "Apple",
    companyAliases: "Apple Inc., AAPL, Apple Computer (former)",
    topIndustrySectorProfile: "Consumer Electronics",
    secondaryIndustrySectorProfile: "Software & Digital Services",
    description: "Apple designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories, and sells a range of related services including the App Store, iCloud, and Apple Pay. It is one of the world's largest companies by revenue and market capitalization.",
    website: "https://www.apple.com",
    companyStructure: "Corporation (California-incorporated public company)",
    ownership: "Public (NASDAQ: AAPL)",
    streetAddress: "One Apple Park Way",
    city: "Cupertino",
    state: "CA",
    zipCode: "95014",
    country: "United States",
    approximateEmployees: "~166,000 full-time equivalent (as of Sept 27, 2025)",
    approximateRevenue: "~$416,200 (FY2025, ended Sept 27, 2025)",
    keyProducts: "iPhone, Mac, iPad, Apple Watch/AirPods (Wearables), Services (App Store, iCloud, Apple Music)",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025 (fiscal year ended Sept 27, 2025, filed Oct 31, 2025) \u2014 https://www.sec.gov/Archives/edgar/data/0000320193/000032019325000079/aapl-20250927.htm",
    linkToReport: rpt("Apple_Partnership_Profile.pdf", "jPYNnQ"),
  }),
  row({
    account: "Bayer (AskBio)",
    companyAliases: "Asklepios BioPharmaceutical, Inc.; AskBio; subsidiary of Bayer AG",
    parentAccount: "Bayer AG",
    topIndustrySectorProfile: "Biotechnology / Gene Therapy",
    secondaryIndustrySectorProfile: "Pharmaceuticals",
    description: "AskBio (Asklepios BioPharmaceutical) is a gene therapy company developing AAV-based treatments for neuromuscular, CNS, cardiovascular, and metabolic diseases, acquired by Bayer AG in 2020. Parent Bayer AG is a German life sciences company operating in pharmaceuticals, consumer health, and crop science.",
    website: "https://www.askbio.com (parent: https://www.bayer.com)",
    companyStructure: "Wholly owned subsidiary of Bayer AG (operates within Bayer's Pharmaceuticals division)",
    ownership: "Public via parent Bayer AG (Frankfurt: BAYN; US OTC ADR: BAYRY)",
    streetAddress: "20 TW Alexander Drive, Suite 110",
    city: "Durham",
    state: "NC",
    zipCode: "27703",
    country: "United States",
    approximateEmployees: "AskBio: not disclosed; Bayer Group: 88,078 (Dec 31, 2025)",
    approximateRevenue: "AskBio: Not disclosed; Bayer Group: \u20ac45,575M (~$49,000M) FY2025",
    keyProducts: "AAV gene therapy platform, Pro10 cell line manufacturing, bemdaneprocel (Parkinson's cell therapy program, with Bayer/BlueRock), AB-1002 (congestive heart failure gene therapy)",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "Bayer Annual Report 2025 (German public company; not SEC 10-K) \u2014 https://www.bayer.com/sites/default/files/2026-03/bayer-annual-report-2025.pdf; AskBio site https://www.askbio.com",
    linkToReport: rpt("Bayer_AskBio_UNC_Partner_Profile.pdf", "m7vIrx"),
  }),
  row({
    account: "BD",
    companyAliases: "BD, Becton Dickinson, BDX",
    topIndustrySectorProfile: "Medical Devices & Technology",
    secondaryIndustrySectorProfile: "Diagnostics & Life Sciences",
    description: "BD is a global medical technology company that manufactures medical devices, instrument systems, and reagents used in medication delivery, infection prevention, diagnostics, and biosciences research. It serves healthcare institutions, clinicians, life science researchers, and the pharmaceutical industry worldwide.",
    website: "https://www.bd.com",
    companyStructure: "Corporation (New Jersey-incorporated public company)",
    ownership: "Public (NYSE: BDX)",
    streetAddress: "1 Becton Drive",
    city: "Franklin Lakes",
    state: "NJ",
    zipCode: "07417",
    country: "United States",
    approximateEmployees: "~72,000 associates in 61 countries (as of Sept 30, 2025)",
    approximateRevenue: "~$21,800 (FY2025, ended Sept 30, 2025)",
    keyProducts: "Syringes and needles (medication delivery), BD Alaris infusion systems, BD MAX/BD Veritor diagnostics, BD FACS flow cytometry, Vacutainer specimen collection",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025 (fiscal year ended Sept 30, 2025, filed Nov 25, 2025) \u2014 https://www.sec.gov/Archives/edgar/data/0000010795/000001079525000099/bdx-20250930.htm",
    linkToReport: rpt("BD_UNC_Partner_Profile.pdf", "48J7m8"),
  }),
  row({
    account: "Blue Cross Blue Shield NC",
    companyAliases: "Blue Cross NC, Blue Cross and Blue Shield of North Carolina, BCBSNC",
    parentAccount: "None (independent licensee of the Blue Cross Blue Shield Association)",
    topIndustrySectorProfile: "Health Insurance / Managed Care",
    secondaryIndustrySectorProfile: "Healthcare Services",
    description: "Blue Cross and Blue Shield of North Carolina is a not-for-profit health insurer serving roughly 2.9 million members across all 100 North Carolina counties. It offers commercial, individual, Medicare, and Medicaid health plans and invests in community health initiatives statewide.",
    website: "https://www.bluecrossnc.com",
    companyStructure: "Not-for-profit, fully taxed North Carolina mutual insurance company; independent BCBSA licensee",
    ownership: "Private (nonprofit; no shareholders)",
    streetAddress: "5901 Chapel Hill Road",
    city: "Durham",
    state: "NC",
    zipCode: "27707",
    country: "United States",
    approximateEmployees: "~5,000",
    approximateRevenue: "~$10,060 (calendar 2025; per statutory filing reported June 2026)",
    keyProducts: "Individual/ACA health plans (Blue Advantage), Employer group plans, Blue Medicare Advantage, Healthy Blue (Medicaid), Dental Blue",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "https://www.bluecrossnc.com (corporate fact sheet at https://mediacenter.bcbsnc.com/resources/reports); 2025 results: https://businessnc.com/n-c-blue-cross-posts-497m-loss-15-revenue-decline-in-2025/",
    linkToReport: rpt("Blue%20Cross%20Blue%20Shield%20NC.pdf", "o240Ym"),
  }),
  row({
    account: "BMS",
    companyAliases: "Bristol Myers Squibb Company, Bristol-Myers Squibb, BMY",
    topIndustrySectorProfile: "Pharmaceuticals / Biopharmaceuticals",
    secondaryIndustrySectorProfile: "Biotechnology (Oncology, Immunology, Cardiovascular, Neuroscience)",
    description: "Bristol Myers Squibb is a global biopharmaceutical company that discovers, develops, and markets medicines in oncology, hematology, immunology, cardiovascular disease, and neuroscience. Its portfolio includes blockbuster therapies such as Opdivo and Eliquis.",
    website: "https://www.bms.com",
    companyStructure: "Corporation (Delaware-incorporated public company)",
    ownership: "Public (NYSE: BMY)",
    streetAddress: "Route 206 & Province Line Road",
    city: "Princeton",
    state: "NJ",
    zipCode: "08543",
    country: "United States",
    approximateEmployees: "~32,500 (2025)",
    approximateRevenue: "~$48,190 (FY2025, ended Dec 31, 2025)",
    keyProducts: "Opdivo, Eliquis, Camzyos, Reblozyl, Breyanzi",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025 (fiscal year ended Dec 31, 2025, filed Feb 2026) \u2014 https://www.sec.gov/Archives/edgar/data/0000014272/000001427226000004/bmy-20251231.htm",
    linkToReport: rpt("BMS_UNC_Partner_Profile.pdf", "YO5nRG"),
  }),
  row({
    account: "Bandwidth",
    companyAliases: "Bandwidth Inc., Bandwidth.com, BAND",
    topIndustrySectorProfile: "Telecommunications / Cloud Communications (CPaaS)",
    secondaryIndustrySectorProfile: "Enterprise Software",
    description: "Bandwidth is a cloud communications platform-as-a-service (CPaaS) company that provides enterprise-grade voice, messaging, and emergency services APIs built on its own nationwide carrier network. It powers communications for platforms such as Microsoft Teams, Zoom, and major contact-center providers.",
    website: "https://www.bandwidth.com",
    companyStructure: "Public corporation (Delaware-incorporated), headquarters-based operating company with international subsidiaries (US, Europe, Asia Pacific)",
    ownership: "Public (NASDAQ: BAND)",
    streetAddress: "2230 Bandmate Way",
    city: "Raleigh",
    state: "NC",
    zipCode: "27607",
    country: "United States",
    approximateEmployees: "~1,100 (as of December 31, 2025)",
    approximateRevenue: "~$754 million (FY2025)",
    keyProducts: "Voice APIs, Messaging APIs, Emergency (911) services, Maestro communications platform, Phone number management",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025, filed February 19, 2026 \u2014 https://www.sec.gov/Archives/edgar/data/0001514416/000151441626000017/band-20251231.htm",
  }),
  row({
    account: "Cisco",
    companyAliases: "Cisco Systems, Inc., CSCO",
    topIndustrySectorProfile: "Networking & Communications Equipment",
    secondaryIndustrySectorProfile: "Cybersecurity & Enterprise Software",
    description: "Cisco is the world's largest networking company, providing switching, routing, wireless, and data-center infrastructure along with security, observability, and collaboration software. It is positioning its portfolio as critical infrastructure for the AI era.",
    website: "https://www.cisco.com",
    companyStructure: "Public corporation with global subsidiaries; segments include Networking, Security, Collaboration, and Observability (includes Splunk)",
    ownership: "Public (NASDAQ: CSCO)",
    streetAddress: "170 West Tasman Drive",
    city: "San Jose",
    state: "CA",
    zipCode: "95134",
    country: "United States",
    approximateEmployees: "~86,200 (end of fiscal 2025)",
    approximateRevenue: "~$56,654 million (FY2025, ended July 26, 2025)",
    keyProducts: "Networking switches and routers, Security (Splunk, Cisco Secure), Webex collaboration, Observability/ThousandEyes, Data center & AI infrastructure",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025 (fiscal year ended July 26, 2025), filed September 2025 \u2014 https://www.sec.gov/Archives/edgar/data/0000858877/000085887725000111/csco-20250726.htm",
    linkToReport: rpt("Cisco_UNC_Partner_Profile.pdf", "19k9wp"),
  }),
  row({
    account: "Databricks",
    companyAliases: "Databricks, Inc.",
    topIndustrySectorProfile: "Data & AI Software (Data Lakehouse / Analytics)",
    secondaryIndustrySectorProfile: "Artificial Intelligence / Machine Learning Platforms",
    description: "Databricks provides the Data Intelligence Platform, a cloud-based \"lakehouse\" that unifies data engineering, analytics, and AI/ML workloads. The company reports a revenue run-rate above $5.4 billion and recently raised equity at a $134 billion valuation.",
    website: "https://www.databricks.com",
    companyStructure: "Privately held venture-backed corporation with 30+ global offices",
    ownership: "Private (venture-backed; investors include Andreessen Horowitz, Thrive, Insight, NVIDIA)",
    streetAddress: "160 Spear Street, 15th Floor",
    city: "San Francisco",
    state: "CA",
    zipCode: "94105",
    country: "United States",
    approximateEmployees: "~15,000+",
    approximateRevenue: "~$5,400 million annualized run-rate (company-announced, early 2026); audited revenue not disclosed",
    keyProducts: "Data Intelligence Platform (lakehouse), Mosaic AI, Lakebase, AI/BI Genie, Unity Catalog",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "https://www.databricks.com/company/newsroom/press-releases/databricks-grows-65-yoy-surpasses-5-4-billion-revenue-run-rate",
    linkToReport: rpt("Databricks_Partnership_Profile.pdf", "19gi4K"),
  }),
  row({
    account: "Duke Energy",
    companyAliases: "Duke Energy Corporation, DUK",
    topIndustrySectorProfile: "Electric Utilities",
    secondaryIndustrySectorProfile: "Natural Gas Distribution",
    description: "Duke Energy is one of the largest US energy holding companies, providing regulated electric service to about 8.6 million customers and natural gas to about 1.7 million customers across the Carolinas, Florida, Indiana, Ohio, Kentucky, and Tennessee. It is executing a major grid and generation investment plan including nuclear and natural gas expansion.",
    website: "https://www.duke-energy.com",
    companyStructure: "Public utility holding company with regulated subsidiaries (Duke Energy Carolinas, Duke Energy Progress, Duke Energy Florida, Duke Energy Indiana, Duke Energy Ohio, Piedmont Natural Gas)",
    ownership: "Public (NYSE: DUK)",
    streetAddress: "526 South Church Street",
    city: "Charlotte",
    state: "NC",
    zipCode: "28202",
    country: "United States",
    approximateEmployees: "~26,400 (as of December 31, 2025)",
    approximateRevenue: "~$32,240 million (FY2025)",
    keyProducts: "Regulated electric generation/transmission/distribution, Natural gas distribution, Nuclear power, Grid modernization, Renewable energy programs",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025, filed February 2026 \u2014 https://www.sec.gov/Archives/edgar/data/0001326160/000132616026000014/duk-20251231.htm",
  }),
  row({
    account: "Eli Lilly",
    companyAliases: "Eli Lilly and Company, Lilly, LLY",
    topIndustrySectorProfile: "Pharmaceuticals / Biotechnology",
    secondaryIndustrySectorProfile: "Life Sciences R&D",
    description: "Eli Lilly is a global pharmaceutical company best known for its blockbuster incretin (GLP-1) medicines Mounjaro and Zepbound, plus major franchises in oncology, immunology, and neuroscience. Revenue grew 45% in 2025, driven largely by its cardiometabolic portfolio.",
    website: "https://www.lilly.com",
    companyStructure: "Public corporation (Indiana-incorporated) with worldwide manufacturing and research subsidiaries",
    ownership: "Public (NYSE: LLY)",
    streetAddress: "Lilly Corporate Center, 893 Delaware Street",
    city: "Indianapolis",
    state: "IN",
    zipCode: "46285",
    country: "United States",
    approximateEmployees: "~50,000 (as of December 31, 2025)",
    approximateRevenue: "~$65,179 million (FY2025)",
    keyProducts: "Mounjaro (tirzepatide), Zepbound, Verzenio, Taltz, Kisunla (donanemab)",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025, filed February 12, 2026 \u2014 https://www.sec.gov/Archives/edgar/data/0000059478/000005947826000013/lly-20251231.htm",
    linkToReport: rpt("EliLilly_UNC_Partner_Profile.pdf", "6Hc14H"),
  }),
  row({
    account: "Epic Games",
    companyAliases: "Epic Games, Inc., Epic",
    parentAccount: "None (independent; minority stakes held by Tencent, Disney, Sony, KIRKBI)",
    topIndustrySectorProfile: "Video Games & Interactive Entertainment",
    secondaryIndustrySectorProfile: "3D Software / Game Engine Technology",
    description: "Epic Games is the developer of Fortnite and the Unreal Engine, a real-time 3D engine used across gaming, film, automotive, and simulation. It also operates the Epic Games Store digital distribution platform.",
    website: "https://www.epicgames.com",
    companyStructure: "Privately held corporation with 40+ offices worldwide",
    ownership: "Private (founder Tim Sweeney majority; Tencent ~40% minority; Disney, Sony, KIRKBI investors)",
    streetAddress: "620 Crossroads Blvd",
    city: "Cary",
    state: "NC",
    zipCode: "27518",
    country: "United States",
    approximateEmployees: "~4,000+ (after announced March 2026 layoffs of over 1,000 staff)",
    approximateRevenue: "Not disclosed (private; third-party estimates vary widely)",
    keyProducts: "Fortnite, Unreal Engine, Epic Games Store, Epic Online Services, Fab marketplace",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "https://www.epicgames.com/site/en-US/about",
    linkToReport: rpt("Epic_Games_Partnership_Profile.pdf", "PyCROc"),
  }),
  row({
    account: "Eshelman Institute for Innovation",
    companyAliases: "Eshelman Innovation, EII",
    parentAccount: "UNC Eshelman School of Pharmacy (University of North Carolina at Chapel Hill)",
    topIndustrySectorProfile: "Higher Education / Academic Research",
    secondaryIndustrySectorProfile: "Healthcare Innovation & Translational Research Funding",
    description: "Eshelman Innovation is a healthcare innovation engine within the UNC Eshelman School of Pharmacy, launched in 2014 with a $100 million gift from Dr. Fred Eshelman. It funds and accelerates translational research in therapeutics and digital health (oncology, infectious disease, neuroscience), having funded 189+ projects with ~$35 million that generated about $251 million in follow-on funding.",
    website: "https://eshelmaninnovation.org",
    companyStructure: "University-internal institute (unit of UNC Eshelman School of Pharmacy, UNC-Chapel Hill)",
    ownership: "Public university entity (part of UNC-Chapel Hill, a state institution)",
    streetAddress: "301 Pharmacy Lane (UNC Eshelman School of Pharmacy, UNC-Chapel Hill campus)",
    city: "Chapel Hill",
    state: "NC",
    zipCode: "27599",
    country: "United States",
    approximateEmployees: "Not disclosed (small institute team within UNC)",
    approximateRevenue: "Not disclosed (endowed by $100M gift; ~$35M deployed since 2015)",
    keyProducts: "Translational research grant funding, Startup creation/acceleration, Drug discovery and digital health commercialization support",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "https://eshelmaninnovation.org/about/ and https://www.unc.edu/posts/2024/03/13/eshelman-innovation-begins-its-second-decade/",
    linkToReport: rpt("Google_Partnership_Profile.pdf", "6KDubq"),
  }),
  row({
    account: "Fred Eshelman",
    companyAliases: "Fredric N. Eshelman, Dr. Fred Eshelman, Eshelman Ventures LLC (investment vehicle)",
    topIndustrySectorProfile: "Philanthropy / Individual Investor",
    secondaryIndustrySectorProfile: "Pharmaceuticals & Life Sciences (CRO, drug development)",
    description: "Founder and former CEO of CRO giant PPD and founding chairman of Furiex Pharmaceuticals, now leading Eshelman Ventures, an investment firm focused on private healthcare companies. He is UNC-Chapel Hill's largest individual donor, having given nearly $140 million to the UNC Eshelman School of Pharmacy, including a $100 million gift establishing the Eshelman Institute for Innovation.",
    website: "https://www.eshelmanventures.com",
    companyStructure: "N/A \u2014 individual (Eshelman Ventures LLC is his private investment company)",
    ownership: "Individual",
    streetAddress: "N/A \u2014 individual (Eshelman Ventures is based in Wilmington, NC)",
    city: "Wilmington",
    state: "NC",
    zipCode: "Not disclosed",
    country: "United States",
    approximateEmployees: "N/A \u2014 individual",
    approximateRevenue: "Not disclosed",
    keyProducts: "Healthcare venture investing, pharmacy education philanthropy, drug development advisory, UNC strategic advising",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "https://www.eshelmanventures.com/about; https://pharmacy.unc.edu/history/",
    linkToReport: rpt("IBM_UNC_Partner_Profile.pdf", "R7ZPUP"),
  }),
  row({
    account: "Google",
    companyAliases: "Google LLC, Alphabet Inc., Alphabet (GOOG/GOOGL)",
    parentAccount: "Alphabet Inc.",
    topIndustrySectorProfile: "Internet Software & Services / Digital Advertising",
    secondaryIndustrySectorProfile: "Cloud Computing & Artificial Intelligence",
    description: "Google, the principal subsidiary of Alphabet Inc., provides internet search, advertising, YouTube, Android, and Google Cloud services worldwide. Alphabet also operates AI research (Google DeepMind) and \"Other Bets\" such as Waymo and Verily.",
    website: "https://www.google.com",
    companyStructure: "Subsidiary (Google LLC) of public holding company Alphabet Inc., Delaware-incorporated",
    ownership: "Public (NASDAQ: GOOGL, GOOG)",
    streetAddress: "1600 Amphitheatre Parkway",
    city: "Mountain View",
    state: "CA",
    zipCode: "94043",
    country: "United States",
    approximateEmployees: "~190,820 (as of December 31, 2025)",
    approximateRevenue: "~$402,836 million (FY2025)",
    keyProducts: "Google Search & advertising, YouTube, Google Cloud, Android/Pixel, Gemini AI",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025 (fiscal year ended Dec 31, 2025), filed February 4, 2026 \u2014 https://www.sec.gov/Archives/edgar/data/0001652044/000165204426000018/goog-20251231.htm",
    linkToReport: rpt("Leidos_Partnership_Profile.pdf", "MjTsmB"),
  }),
  row({
    account: "Golden LEAF Foundation",
    companyAliases: "The Golden LEAF (Long-term Economic Advancement Foundation), Golden Leaf Foundation Inc.",
    topIndustrySectorProfile: "Philanthropic Grantmaking / Economic Development",
    secondaryIndustrySectorProfile: "Rural & Agricultural Development, Workforce Education",
    description: "A nonprofit created in 1999 to receive 50% of North Carolina's payments from the tobacco Master Settlement Agreement. It makes grants to increase economic opportunity in North Carolina's rural and tobacco-dependent communities through economic development, agriculture, and workforce initiatives.",
    website: "https://goldenleaf.org",
    companyStructure: "Independent 501(c)(3) nonprofit foundation",
    ownership: "Nonprofit",
    streetAddress: "301 N. Winstead Avenue",
    city: "Rocky Mount",
    state: "NC",
    zipCode: "27804",
    country: "United States",
    approximateEmployees: "Not disclosed (small foundation staff)",
    approximateRevenue: "Not disclosed (endowment-funded; investment income covers operations and has funded hundreds of millions in grants)",
    keyProducts: "Economic development grants, agriculture grants, workforce/education grants, Golden LEAF Scholarships, rural infrastructure funding",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "https://goldenleaf.org (grant database: https://goldenleaf.org/grant-search/)",
    linkToReport: rpt("GoldenLEAF_UNC_Partner_Profile.pdf", "d6C3m9"),
  }),
  row({
    account: "IBM",
    companyAliases: "International Business Machines Corporation, IBM Corp., Big Blue",
    topIndustrySectorProfile: "Information Technology \u2014 Hybrid Cloud & Software",
    secondaryIndustrySectorProfile: "IT Consulting & AI Services",
    description: "IBM is a global technology company providing hybrid cloud and AI software, consulting services, and enterprise infrastructure such as mainframes and quantum computing. Its portfolio centers on Red Hat, watsonx AI, automation, data, and security software.",
    website: "https://www.ibm.com",
    companyStructure: "Public corporation (incorporated in New York)",
    ownership: "Public (NYSE: IBM)",
    streetAddress: "One New Orchard Road",
    city: "Armonk",
    state: "NY",
    zipCode: "10504",
    country: "United States",
    approximateEmployees: "~286,800 total workforce as of Dec 31, 2025 (264,300 IBM employees plus subsidiaries and temporary/part-time)",
    approximateRevenue: "~$67,500 million (FY2025)",
    keyProducts: "Hybrid cloud (Red Hat), watsonx AI platform, IBM Consulting, IBM Z mainframes, quantum computing",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025 (fiscal year ended Dec 31, 2025), filed February 24, 2026 \u2014 https://www.sec.gov/Archives/edgar/data/0000051143/000005114326000010/ibm-20251231.htm",
    linkToReport: rpt("Lenovo_UNC_Partner_Profile.pdf", "TZ67oe"),
  }),
  row({
    account: "GSK",
    companyAliases: "GSK plc, GlaxoSmithKline, Glaxo",
    topIndustrySectorProfile: "Pharmaceuticals & Biotechnology",
    secondaryIndustrySectorProfile: "Vaccines",
    description: "GSK is a UK-headquartered global biopharmaceutical company focused on specialty medicines (HIV, oncology, respiratory, immunology) and vaccines. It files in the US as a foreign private issuer on Form 20-F and has major US operations including in the Research Triangle region.",
    website: "https://www.gsk.com",
    companyStructure: "UK public limited company (plc); US-listed via ADRs",
    ownership: "Public (LSE: GSK; NYSE: GSK ADR)",
    streetAddress: "79 New Oxford Street",
    city: "London",
    state: "N/A (UK)",
    zipCode: "WC1A 1DG",
    country: "United Kingdom",
    approximateEmployees: "~66,800 across ~70 countries (2025 annual report)",
    approximateRevenue: "\u00a332,700 million turnover FY2025 (~$41,000\u201342,000 million)",
    keyProducts: "Shingrix, Arexvy, HIV medicines (Dovato, Cabenuva via ViiV), Trelegy, oncology portfolio (e.g., Jemperli)",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 20-F FY2025 (year ended Dec 31, 2025), filed March 6, 2026 \u2014 https://www.sec.gov/Archives/edgar/data/0001131399/000113139926000004/gsk-20251231.htm",
    linkToReport: rpt("GSK_UNC_Partner_Profile.pdf", "IXn0Xu"),
  }),
  row({
    account: "Hatteras Venture Partners",
    companyAliases: "Hatteras VP, Hatteras Venture Partners LLC",
    topIndustrySectorProfile: "Venture Capital \u2014 Life Sciences",
    secondaryIndustrySectorProfile: "Biotechnology, MedTech & Health Technology",
    description: "Founded in 2000, Hatteras Venture Partners is a Durham, NC-based early-stage venture capital firm investing in biotech, medtech, and health technology companies across North America. The firm has roughly $900 million under management across seven funds and has invested in 100+ companies.",
    website: "https://hatterasvp.com",
    companyStructure: "Private venture capital partnership (LLC/LP fund structure)",
    ownership: "Private",
    streetAddress: "280 S. Mangum Street, Suite 350",
    city: "Durham",
    state: "NC",
    zipCode: "27701",
    country: "United States",
    approximateEmployees: "Not disclosed (small investment team)",
    approximateRevenue: "Not disclosed",
    keyProducts: "Early-stage biotech investing, medtech/device investing, health tech/digital health investing, company formation support",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "https://hatterasvp.com",
    linkToReport: rpt("Hatteras_UNC_Partner_Profile.pdf", "S2NZpk"),
  }),
  row({
    account: "IQVIA",
    companyAliases: "IQVIA Holdings Inc., Quintiles IMS (former), Quintiles, IMS Health",
    topIndustrySectorProfile: "Life Sciences \u2014 Contract Research & Clinical Trials (CRO)",
    secondaryIndustrySectorProfile: "Healthcare Data Analytics & Technology",
    description: "IQVIA is a leading global provider of clinical research services, healthcare data analytics, and technology solutions for the life sciences industry, formed by the 2016 merger of Quintiles and IMS Health. It runs clinical trials and supplies real-world evidence and commercial analytics to pharma and biotech clients worldwide.",
    website: "https://www.iqvia.com",
    companyStructure: "Public holding company (Delaware-incorporated)",
    ownership: "Public (NYSE: IQV)",
    streetAddress: "2400 Ellis Road",
    city: "Durham",
    state: "NC",
    zipCode: "27703",
    country: "United States",
    approximateEmployees: "~88,000",
    approximateRevenue: "~$16,310 million (FY2025)",
    keyProducts: "Clinical trial/CRO services (R&D Solutions), real-world evidence, healthcare data & analytics (Connected Intelligence), commercial/Technology & Analytics Solutions, contract sales & medical solutions",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025 (fiscal year ended Dec 31, 2025), filed February 2026 \u2014 https://s201.q4cdn.com/580005511/files/doc_financials/2025/q4/IQV-2025-12-31-10K_Filed-with-exhibits.pdf (EDGAR: https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0001478242&type=10-K)",
    linkToReport: rpt("IQVIA_UNC_Partner_Profile.pdf", "6wFU7v"),
  }),
  row({
    account: "Johnson & Johnson",
    companyAliases: "J&J, Janssen, Johnson and Johnson, JNJ, Johnson & Johnson Innovative Medicine, Johnson & Johnson MedTech",
    topIndustrySectorProfile: "Pharmaceuticals / Biotechnology",
    secondaryIndustrySectorProfile: "Medical Devices & Technology",
    description: "Johnson & Johnson is a global healthcare company that researches, develops, manufactures, and sells pharmaceuticals and medical technologies. It operates in two segments \u2014 Innovative Medicine and MedTech \u2014 serving patients in virtually every country.",
    website: "https://www.jnj.com",
    companyStructure: "Public corporation incorporated in New Jersey; parent of a global family of operating subsidiaries organized in two business segments (Innovative Medicine and MedTech)",
    ownership: "Public (NYSE: JNJ)",
    streetAddress: "One Johnson & Johnson Plaza",
    city: "New Brunswick",
    state: "NJ",
    zipCode: "08933",
    country: "United States",
    approximateEmployees: "~138,200 (worldwide, per FY2025 10-K)",
    approximateRevenue: "~$94,200 million (FY2025 worldwide sales of $94.2 billion)",
    keyProducts: "Darzalex, Stelara, Tremfya, Carvykti, surgical and orthopaedic/cardiovascular medical devices",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025 (fiscal year ended December 28, 2025), filed February 11, 2026 \u2014 https://www.sec.gov/Archives/edgar/data/0000200406/000020040626000016/jnj-20251228.htm",
    linkToReport: rpt("JohnsonJohnson_UNC_Partner_Profile.pdf", "Evo9ds"),
  }),
  row({
    account: "Labcorp",
    companyAliases: "Labcorp Holdings Inc., Laboratory Corporation of America Holdings, LabCorp, LH",
    topIndustrySectorProfile: "Clinical Laboratory & Diagnostics Services",
    secondaryIndustrySectorProfile: "Biopharma Laboratory Services / Drug Development",
    description: "Labcorp is a global laboratory services company providing clinical diagnostic testing and biopharma laboratory services (central labs and early development) to physicians, hospitals, health systems, and drug developers. It serves clients in roughly 100 countries.",
    website: "https://www.labcorp.com",
    companyStructure: "Public holding company (Labcorp Holdings Inc., a Delaware corporation) with two segments: Diagnostics Laboratories and Biopharma Laboratory Services",
    ownership: "Public (NYSE: LH)",
    streetAddress: "358 South Main Street",
    city: "Burlington",
    state: "NC",
    zipCode: "27215",
    country: "United States",
    approximateEmployees: "~71,000 (per FY2025 10-K)",
    approximateRevenue: "~$13,952 million (FY2025 revenues of $13,951.7 million)",
    keyProducts: "Clinical diagnostic testing, specialty/esoteric testing, central laboratory services for clinical trials, early drug development services, health data/analytics",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025, filed February 24, 2026 \u2014 https://www.sec.gov/Archives/edgar/data/920148/000092014826000111/lh-20251231.htm",
    linkToReport: rpt("Labcorp_Profile_6_9_2026.pdf", "XBHvlq"),
  }),
  row({
    account: "Leidos",
    companyAliases: "Leidos Holdings, Inc., Leidos Inc., LDOS (formerly SAIC/Science Applications International Corporation heritage)",
    topIndustrySectorProfile: "Defense & Government IT Services",
    secondaryIndustrySectorProfile: "Health & Civil Technology Services",
    description: "Leidos is a technology and engineering services company delivering digital, mission software, and integration solutions to U.S. defense, intelligence, homeland security, civil, and health customers. Its segments include National Security & Digital, Health & Civil, Commercial & International, and Defense Systems.",
    website: "https://www.leidos.com",
    companyStructure: "Public holding company (Leidos Holdings, Inc., a Delaware corporation) operating through four reportable segments",
    ownership: "Public (NYSE: LDOS)",
    streetAddress: "1750 Presidents Street",
    city: "Reston",
    state: "VA",
    zipCode: "20190",
    country: "United States",
    approximateEmployees: "~47,000 (as of January 2, 2026, per FY2025 10-K)",
    approximateRevenue: "~$17,174 million (FY2025 revenues)",
    keyProducts: "Digital modernization and IT services, mission software systems, intelligence community solutions, managed health services (e.g., disability exams), security detection and defense systems",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025 (fiscal year ended January 2, 2026), filed February 17, 2026 \u2014 https://www.sec.gov/Archives/edgar/data/1336920/000133692026000030/ldos-20260102.htm",
    linkToReport: rpt("Leidos_Partnership_Profile.pdf", "SWegHO"),
  }),
  row({
    account: "Lenovo",
    companyAliases: "Lenovo Group Limited, Lenovo (United States) Inc., Legend (historical), LNVGY (ADR)",
    parentAccount: "Lenovo Group Limited (Hong Kong-listed parent of U.S. subsidiary)",
    topIndustrySectorProfile: "Computer Hardware / Consumer Electronics",
    secondaryIndustrySectorProfile: "Data Center Infrastructure & AI Solutions",
    description: "Lenovo is a global technology company and the world's largest PC maker, producing PCs, smartphones, servers, and AI/data-center infrastructure and solutions. It is a Chinese-origin multinational listed in Hong Kong, with its U.S. headquarters in Morrisville, North Carolina.",
    website: "https://www.lenovo.com",
    companyStructure: "Publicly listed parent (Lenovo Group Limited, HKEX: 0992) with business groups: Intelligent Devices Group, Infrastructure Solutions Group, and Solutions & Services Group; U.S. operations via Lenovo (United States) Inc.",
    ownership: "Public (HKEX: 0992; OTC ADR: LNVGY)",
    streetAddress: "8001 Development Drive (U.S. headquarters)",
    city: "Morrisville",
    state: "NC",
    zipCode: "27560",
    country: "United States (U.S. HQ; parent headquartered in Beijing/Hong Kong)",
    approximateEmployees: "~73,500 worldwide (end of FY2025/26)",
    approximateRevenue: "~$83,100 million (FY2025/26 revenue of US$83.1 billion, fiscal year ended March 31, 2026)",
    keyProducts: "ThinkPad and Yoga PCs, ThinkSystem servers, Motorola smartphones, AI infrastructure and data center solutions, TruScale services",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "Lenovo FY2025/26 Q4 and full-year results announcement (May 2026) \u2014 https://investor.lenovo.com/en/financial/results/press_2526_q4.pdf ; https://news.lenovo.com/pressroom/press-releases/fy-2025-26/ (not SEC-registered; HKEX filer)",
    linkToReport: rpt("Meta_Partnership_Profile.pdf", "FIKd9j"),
  }),
  row({
    account: "Lockheed Martin",
    companyAliases: "Lockheed Martin Corporation, LMT, Lockheed",
    topIndustrySectorProfile: "Aerospace & Defense",
    secondaryIndustrySectorProfile: "Space Systems & Government Technology",
    description: "Lockheed Martin is a global security and aerospace company engaged in the research, design, development, manufacture, and sustainment of advanced technology systems, principally for the U.S. government. Its segments are Aeronautics, Missiles and Fire Control, Rotary and Mission Systems, and Space.",
    website: "https://www.lockheedmartin.com",
    companyStructure: "Public corporation incorporated in Maryland with four reportable business segments",
    ownership: "Public (NYSE: LMT)",
    streetAddress: "6801 Rockledge Drive",
    city: "Bethesda",
    state: "MD",
    zipCode: "20817",
    country: "United States",
    approximateEmployees: "~123,000 (as of December 31, 2025, including ~72,000 engineers/scientists, per FY2025 10-K)",
    approximateRevenue: "~$75,048 million (FY2025 total net sales)",
    keyProducts: "F-35 Lightning II, Sikorsky helicopters (Black Hawk), PAC-3 and HIMARS missile systems, Aegis combat system, satellites and space systems (Orion, Next Gen Interceptor)",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025, filed January 29, 2026 \u2014 https://www.sec.gov/Archives/edgar/data/936468/000162828026004195/lmt-20251231.htm",
    linkToReport: rpt("Microsoft_Partnership_Profile.pdf", "k7YntB"),
  }),
  row({
    account: "Merck",
    companyAliases: "Merck & Co., Inc., MSD (Merck Sharp & Dohme, outside US/Canada), MRK",
    topIndustrySectorProfile: "Pharmaceuticals / Biotechnology",
    secondaryIndustrySectorProfile: "Animal Health",
    description: "Merck & Co. is a global biopharmaceutical company that discovers, develops, manufactures, and markets prescription medicines, vaccines, and animal health products. Known as MSD outside the United States and Canada, it operates Pharmaceutical and Animal Health segments.",
    website: "https://www.merck.com",
    companyStructure: "Public corporation incorporated in New Jersey with two reportable segments: Pharmaceutical and Animal Health",
    ownership: "Public (NYSE: MRK)",
    streetAddress: "126 East Lincoln Avenue",
    city: "Rahway",
    state: "NJ",
    zipCode: "07065",
    country: "United States",
    approximateEmployees: "~75,000 worldwide (as of December 31, 2025, per FY2025 10-K)",
    approximateRevenue: "~$65,011 million (FY2025 total sales)",
    keyProducts: "Keytruda, Gardasil/Gardasil 9, Winrevair, Januvia, Bravecto (animal health)",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025, filed February 24, 2026 \u2014 https://www.sec.gov/Archives/edgar/data/310158/000031015826000063/mrk-20251231.htm",
    linkToReport: rpt("Merck_UNC_Partner_Profile.pdf", "5f2peS"),
  }),
  row({
    account: "NC Commerce",
    companyAliases: "NC Department of Commerce, North Carolina Department of Commerce, NC DOC, Commerce NC",
    parentAccount: "State of North Carolina",
    topIndustrySectorProfile: "Government \u2014 Economic Development",
    secondaryIndustrySectorProfile: "Workforce Development & Employment Services",
    description: "The North Carolina Department of Commerce is the state's lead agency for economic, community, and workforce development, with a mission to improve the economic well-being and quality of life for all North Carolinians. It manages business recruitment, rural development grants, tourism marketing, labor market data, and employment security programs.",
    website: "https://www.commerce.nc.gov",
    companyStructure: "Cabinet-level state government agency led by a Secretary of Commerce appointed by the Governor; includes divisions such as Employment Security, Workforce Solutions, and Rural Economic Development, plus the affiliated Economic Development Partnership of NC",
    ownership: "Government (State of North Carolina)",
    streetAddress: "301 N. Wilmington Street",
    city: "Raleigh",
    state: "NC",
    zipCode: "27601",
    country: "United States",
    approximateEmployees: "Not disclosed",
    approximateRevenue: "Not disclosed (annual state budget appropriation; figure not published on official site)",
    keyProducts: "Business recruitment and expansion incentives, workforce development programs (NCWorks), unemployment insurance administration, rural community grants, labor market data and analysis",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "https://www.commerce.nc.gov/about-us",
    linkToReport: rpt("NCCommerce_UNC_Partner_Profile.pdf", "LiDAUI"),
  }),
  row({
    account: "Meta",
    companyAliases: "Meta Platforms, Inc.; Facebook, Inc. (former name); Meta Platforms; FB",
    topIndustrySectorProfile: "Social Media & Internet Services",
    secondaryIndustrySectorProfile: "Artificial Intelligence / Virtual & Augmented Reality",
    description: "Meta builds social networking and messaging apps \u2014 Facebook, Instagram, WhatsApp, and Messenger \u2014 used by billions of people, monetized primarily through digital advertising. It also invests heavily in AI and in virtual/augmented reality hardware through its Reality Labs division.",
    website: "https://www.meta.com",
    companyStructure: "Public corporation (Delaware); two segments: Family of Apps and Reality Labs",
    ownership: "Public (NASDAQ: META)",
    streetAddress: "1 Hacker Way",
    city: "Menlo Park",
    state: "CA",
    zipCode: "94025",
    country: "United States",
    approximateEmployees: "78,865 (as of December 31, 2025)",
    approximateRevenue: "~$200,966M (FY2025)",
    keyProducts: "Facebook, Instagram, WhatsApp, Messenger, Meta Quest / Ray-Ban Meta AI glasses",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025, filed January 28, 2026 \u2014 https://www.sec.gov/Archives/edgar/data/0001326801/000162828026003942/meta-20251231.htm",
    linkToReport: rpt("NVIDIA_Partnership_Profile.pdf", "F43erM"),
  }),
  row({
    account: "Microsoft",
    companyAliases: "Microsoft Corporation; MSFT; Microsoft Corp",
    topIndustrySectorProfile: "Software & Cloud Computing",
    secondaryIndustrySectorProfile: "Artificial Intelligence / Enterprise IT",
    description: "Microsoft develops software, cloud services, devices, and AI solutions, including Windows, Office/Microsoft 365, and the Azure cloud platform. It is one of the world's largest technology companies, serving consumers and enterprises globally.",
    website: "https://www.microsoft.com",
    companyStructure: "Public corporation (Washington); three segments: Productivity and Business Processes, Intelligent Cloud, More Personal Computing",
    ownership: "Public (NASDAQ: MSFT)",
    streetAddress: "One Microsoft Way",
    city: "Redmond",
    state: "WA",
    zipCode: "98052-6399",
    country: "United States",
    approximateEmployees: "~228,000 (as of June 30, 2025)",
    approximateRevenue: "~$281,700M (FY2025, ended June 30, 2025)",
    keyProducts: "Azure, Microsoft 365/Office, Windows, Copilot AI, Xbox, LinkedIn",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025, filed July 30, 2025 \u2014 https://www.sec.gov/Archives/edgar/data/0000789019/000095017025100235/msft-20250630.htm",
    linkToReport: rpt("Microsoft_Partnership_Profile.pdf", "XiSJJk"),
  }),
  row({
    account: "NVIDIA",
    companyAliases: "NVIDIA Corporation; NVDA; Nvidia",
    topIndustrySectorProfile: "Semiconductors",
    secondaryIndustrySectorProfile: "Artificial Intelligence / Data Center Computing",
    description: "NVIDIA designs GPUs and full-stack accelerated computing platforms that power AI training and inference, data centers, gaming, and professional visualization. Its data center chips and CUDA software are the dominant infrastructure for the AI industry.",
    website: "https://www.nvidia.com",
    companyStructure: "Public corporation (Delaware); two segments: Compute & Networking and Graphics",
    ownership: "Public (NASDAQ: NVDA)",
    streetAddress: "2788 San Tomas Expressway",
    city: "Santa Clara",
    state: "CA",
    zipCode: "95051",
    country: "United States",
    approximateEmployees: "~42,000 (as of January 25, 2026)",
    approximateRevenue: "~$215,938M (FY2026, ended January 25, 2026)",
    keyProducts: "Data center GPUs (Blackwell/Hopper), GeForce gaming GPUs, CUDA software platform, DGX/HGX AI systems, networking (NVLink/InfiniBand)",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2026, filed February 25, 2026 \u2014 https://www.sec.gov/Archives/edgar/data/0001045810/000104581026000021/nvda-20260125.htm",
    linkToReport: rpt("Oracle_Partnership_Profile.pdf", "4VilOX"),
  }),
  row({
    account: "NCDHHS",
    companyAliases: "North Carolina Department of Health and Human Services; NC DHHS; NCDHHS",
    parentAccount: "State of North Carolina",
    topIndustrySectorProfile: "Government \u2014 Health & Human Services",
    secondaryIndustrySectorProfile: "Public Health / Social Services",
    description: "NCDHHS manages the delivery of health and human services for all North Carolinians, especially vulnerable populations such as children, the elderly, people with disabilities, and low-income families. It operates 33 divisions and offices and oversees 14 state facilities, including the state Medicaid program.",
    website: "https://www.ncdhhs.gov",
    companyStructure: "State government cabinet agency with 33 divisions/offices and 14 state-operated facilities",
    ownership: "Government (State of North Carolina)",
    streetAddress: "1915 Health Services Way",
    city: "Raleigh",
    state: "NC",
    zipCode: "27607",
    country: "United States",
    approximateEmployees: "~18,000\u201319,000 (second-largest NC state agency)",
    approximateRevenue: "~$7,670M net state General Fund appropriation (FY2024-25); total all-funds budget including federal Medicaid funds is substantially larger",
    keyProducts: "NC Medicaid, public health programs, behavioral health and state-operated facilities, child and family social services, vital records",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "https://www.ncdhhs.gov/about/overview; NC General Assembly HHS budget highlights \u2014 https://webservices.ncleg.gov/ViewDocSiteFile/83432",
    linkToReport: rpt("NCDHHS_UNC_Partner_Profile.pdf", "bX1RQJ"),
  }),
  row({
    account: "OpenAI",
    companyAliases: "OpenAI, Inc.; OpenAI Group PBC; OpenAI Foundation; OpenAI LP (former)",
    parentAccount: "OpenAI Foundation (nonprofit, controls OpenAI Group PBC)",
    topIndustrySectorProfile: "Artificial Intelligence",
    secondaryIndustrySectorProfile: "Software / Cloud Services",
    description: "OpenAI is an AI research and product company best known for ChatGPT and the GPT family of foundation models, with a stated mission of ensuring artificial general intelligence benefits all of humanity. It operates as a for-profit public benefit corporation controlled by a nonprofit foundation.",
    website: "https://www.openai.com",
    companyStructure: "Nonprofit (OpenAI Foundation) controlling a for-profit public benefit corporation (OpenAI Group PBC)",
    ownership: "Private (nonprofit-controlled; Microsoft holds a significant minority stake)",
    streetAddress: "Not disclosed (offices in Mission Bay, San Francisco)",
    city: "San Francisco",
    state: "CA",
    zipCode: "94158",
    country: "United States",
    approximateEmployees: "Not disclosed (media reports ~3,000+)",
    approximateRevenue: "Not disclosed (private; media reports placed annualized revenue above $10,000M in 2025, unverified)",
    keyProducts: "ChatGPT, GPT model APIs, Sora, DALL-E, Codex",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "https://openai.com (company and structure pages: https://openai.com/our-structure/)",
    linkToReport: rpt("OpenAI_Partnership_Profile.pdf", "0so8wa"),
  }),
  row({
    account: "Oracle",
    companyAliases: "Oracle Corporation; ORCL; Oracle Corp",
    topIndustrySectorProfile: "Enterprise Software & Database",
    secondaryIndustrySectorProfile: "Cloud Infrastructure",
    description: "Oracle provides enterprise database software, cloud applications (ERP, HCM, CX), and Oracle Cloud Infrastructure (OCI), serving businesses and governments worldwide. It has become a major provider of AI and cloud computing infrastructure.",
    website: "https://www.oracle.com",
    companyStructure: "Public corporation (Delaware); segments: Cloud and License, Hardware, Services",
    ownership: "Public (NYSE: ORCL)",
    streetAddress: "2300 Oracle Way",
    city: "Austin",
    state: "TX",
    zipCode: "78741",
    country: "United States",
    approximateEmployees: "~162,000 (as of May 31, 2025)",
    approximateRevenue: "~$57,400M (FY2025, ended May 31, 2025)",
    keyProducts: "Oracle Database, Oracle Cloud Infrastructure (OCI), Fusion Cloud Applications (ERP/HCM), NetSuite, MySQL/Java",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025, filed June 18, 2025 \u2014 https://www.sec.gov/Archives/edgar/data/0001341439/000095017025087926/orcl-20250531.htm",
    linkToReport: rpt("RedHat_IBM_UNC_Partner_Profile.pdf", "XvL3qS"),
  }),
  row({
    account: "Pfizer",
    companyAliases: "Pfizer Inc.; PFE; Pfizer",
    topIndustrySectorProfile: "Pharmaceuticals & Biotechnology",
    secondaryIndustrySectorProfile: "Life Sciences / Vaccines",
    description: "Pfizer is a global biopharmaceutical company that discovers, develops, manufactures, and sells medicines and vaccines across oncology, internal medicine, vaccines, and inflammation/immunology. Its products are sold in markets worldwide.",
    website: "https://www.pfizer.com",
    companyStructure: "Public corporation (Delaware); operates primarily through Biopharma, its global biopharmaceutical operating segment",
    ownership: "Public (NYSE: PFE)",
    streetAddress: "66 Hudson Boulevard East",
    city: "New York",
    state: "NY",
    zipCode: "10001",
    country: "United States",
    approximateEmployees: "~75,000 (as of December 31, 2025, per 10-K)",
    approximateRevenue: "~$62,600M (FY2025)",
    keyProducts: "Eliquis, Prevnar vaccine family, Comirnaty, Paxlovid, Ibrance/oncology portfolio",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025, filed February 26, 2026 \u2014 https://www.sec.gov/Archives/edgar/data/0000078003/000007800326000026/pfe-20251231.htm",
    linkToReport: rpt("Pfizer_Profile_6_9_2026.pdf", "qNNHMe"),
  }),
  row({
    account: "Palantir Technologies",
    companyAliases: "Palantir, Palantir Technologies Inc., PLTR",
    topIndustrySectorProfile: "Software \u2014 Data Analytics & AI Platforms",
    secondaryIndustrySectorProfile: "Defense & Government IT",
    description: "Palantir builds software platforms (Gotham, Foundry, AIP) that help governments and large enterprises integrate, analyze, and act on their data. It is a major supplier of AI and data-integration software to U.S. defense, intelligence, and commercial customers.",
    website: "https://www.palantir.com",
    companyStructure: "Corporation (Delaware-incorporated public company)",
    ownership: "Public (Nasdaq: PLTR)",
    streetAddress: "1200 17th Street, Floor 15",
    city: "Denver",
    state: "CO",
    zipCode: "80202",
    country: "USA",
    approximateEmployees: "4,429 full-time (as of Dec 31, 2025)",
    approximateRevenue: "~$4,475 M (FY2025)",
    keyProducts: "Gotham, Foundry, AIP (Artificial Intelligence Platform), Apollo",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025, filed Feb 17, 2026 \u2014 https://investors.palantir.com/files/2025%20FY%20PLTR%2010-K.pdf (EDGAR CIK 1321655)",
    linkToReport: rpt("Salesforce_Partnership_Profile.pdf", "yrNeIU"),
  }),
  row({
    account: "Red Hat (IBM)",
    companyAliases: "International Business Machines Corporation, IBM Corp., Big Blue",
    topIndustrySectorProfile: "Information Technology \u2014 Hybrid Cloud & Software",
    secondaryIndustrySectorProfile: "IT Consulting & AI Services",
    description: "IBM is a global technology company providing hybrid cloud and AI software, consulting services, and enterprise infrastructure such as mainframes and quantum computing. Its portfolio centers on Red Hat, watsonx AI, automation, data, and security software.",
    website: "https://www.ibm.com",
    companyStructure: "Public corporation (incorporated in New York)",
    ownership: "Public (NYSE: IBM)",
    streetAddress: "One New Orchard Road",
    city: "Armonk",
    state: "NY",
    zipCode: "10504",
    country: "United States",
    approximateEmployees: "~286,800 total workforce as of Dec 31, 2025 (264,300 IBM employees plus subsidiaries and temporary/part-time)",
    approximateRevenue: "~$67,500 million (FY2025)",
    keyProducts: "Hybrid cloud (Red Hat), watsonx AI platform, IBM Consulting, IBM Z mainframes, quantum computing",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025 (fiscal year ended Dec 31, 2025), filed February 24, 2026 \u2014 https://www.sec.gov/Archives/edgar/data/0000051143/000005114326000010/ibm-20251231.htm",
    linkToReport: rpt("SAS_Institute_UNC_Partner_Profile.pdf", "53M9cQ"),
  }),
  row({
    account: "Salesforce",
    companyAliases: "Salesforce, Inc.; salesforce.com; CRM",
    topIndustrySectorProfile: "Software \u2014 CRM & Enterprise Cloud Applications (SaaS)",
    secondaryIndustrySectorProfile: "Artificial Intelligence \u2014 Agentic AI Platforms",
    description: "Salesforce is the world's largest provider of customer relationship management (CRM) software, delivered as cloud services spanning sales, service, marketing, commerce, and analytics. Its Agentforce 360 platform embeds autonomous AI agents across business functions.",
    website: "https://www.salesforce.com",
    companyStructure: "Corporation (Delaware-incorporated public company)",
    ownership: "Public (NYSE: CRM)",
    streetAddress: "Salesforce Tower, 415 Mission Street, 3rd Floor",
    city: "San Francisco",
    state: "CA",
    zipCode: "94105",
    country: "USA",
    approximateEmployees: "83,334 (as of Jan 31, 2026)",
    approximateRevenue: "~$41,500 M (FY2026, ended Jan 31, 2026; up 10% YoY)",
    keyProducts: "Sales Cloud, Service Cloud, Agentforce 360, Tableau, MuleSoft/Slack",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2026 (period ended Jan 31, 2026), filed Mar 2, 2026 \u2014 https://www.sec.gov/Archives/edgar/data/0001108524/000110852426000060/crm-20260131.htm",
    linkToReport: rpt("Snowflake_Partnership_Profile.pdf", "0KVVb3"),
  }),
  row({
    account: "SAS Institute",
    companyAliases: "SAS, SAS Institute Inc.",
    topIndustrySectorProfile: "Software \u2014 Advanced Analytics & AI",
    secondaryIndustrySectorProfile: "Data Management & Business Intelligence",
    description: "SAS is a privately held global software company, marking 50 years of analytics innovation, that provides advanced analytics, AI, and data-management solutions to organizations in more than 150 countries. Its flagship SAS Viya platform serves industries from banking and insurance to government and life sciences.",
    website: "https://www.sas.com",
    companyStructure: "Privately held corporation (founder-owned)",
    ownership: "Private",
    streetAddress: "100 SAS Campus Drive",
    city: "Cary",
    state: "NC",
    zipCode: "27513",
    country: "USA",
    approximateEmployees: "~12,000",
    approximateRevenue: "~$3,000 M (latest publicly reported, FY2024; private company \u2014 not formally disclosed)",
    keyProducts: "SAS Viya, SAS 9 analytics platform, SAS Visual Analytics, industry AI/fraud and risk solutions",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "https://www.sas.com/en_us/company-information.html (private company; figures per company profile sources, e.g., https://craft.co/sas)",
    linkToReport: rpt("Splunk_Cisco_UNC_Partner_Profile.pdf", "4cXuMP"),
  }),
  row({
    account: "Snowflake",
    companyAliases: "Snowflake Inc., SNOW",
    topIndustrySectorProfile: "Software \u2014 Cloud Data Platform / Data Warehousing",
    secondaryIndustrySectorProfile: "Artificial Intelligence & Data Analytics",
    description: "Snowflake provides the AI Data Cloud, a cloud-native platform that lets organizations consolidate, share, and analyze data and build AI applications across AWS, Azure, and Google Cloud. It ended FY2026 with 13,328 customers worldwide.",
    website: "https://www.snowflake.com",
    companyStructure: "Corporation (Delaware-incorporated public company); operates a globally distributed \"headquarterless\" model",
    ownership: "Public (NYSE: SNOW)",
    streetAddress: "135 Constitution Drive (principal executive offices per FY2026 10-K; note \u2014 earlier filings listed Bozeman, MT, but the current 10-K lists Menlo Park)",
    city: "Menlo Park",
    state: "CA",
    zipCode: "94025",
    country: "USA",
    approximateEmployees: "9,060 across 36 countries (as of Jan 31, 2026)",
    approximateRevenue: "~$4,700 M (FY2026, ended Jan 31, 2026)",
    keyProducts: "AI Data Cloud, Snowflake Data Warehouse, Snowpark, Cortex AI, Snowflake Marketplace",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2026 (period ended Jan 31, 2026), filed/signed Mar 20, 2026 \u2014 https://www.sec.gov/Archives/edgar/data/0001640147/000164014726000008/snow-20260131.htm",
    linkToReport: rpt("Snowflake_Partnership_Profile.pdf", "ceIAHB"),
  }),
  row({
    account: "Splunk (Cisco)",
    companyAliases: "Cisco Systems, Inc., CSCO",
    topIndustrySectorProfile: "Networking & Communications Equipment",
    secondaryIndustrySectorProfile: "Cybersecurity & Enterprise Software",
    description: "Cisco is the world's largest networking company, providing switching, routing, wireless, and data-center infrastructure along with security, observability, and collaboration software. It is positioning its portfolio as critical infrastructure for the AI era.",
    website: "https://www.cisco.com",
    companyStructure: "Public corporation with global subsidiaries; segments include Networking, Security, Collaboration, and Observability (includes Splunk)",
    ownership: "Public (NASDAQ: CSCO)",
    streetAddress: "170 West Tasman Drive",
    city: "San Jose",
    state: "CA",
    zipCode: "95134",
    country: "United States",
    approximateEmployees: "~86,200 (end of fiscal 2025)",
    approximateRevenue: "~$56,654 million (FY2025, ended July 26, 2025)",
    keyProducts: "Networking switches and routers, Security (Splunk, Cisco Secure), Webex collaboration, Observability/ThousandEyes, Data center & AI infrastructure",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "SEC Form 10-K FY2025 (fiscal year ended July 26, 2025), filed September 2025 \u2014 https://www.sec.gov/Archives/edgar/data/0000858877/000085887725000111/csco-20250726.htm",
    linkToReport: rpt("Splunk_Cisco_UNC_Partner_Profile.pdf", "H4oJeG"),
  }),
  row({
    account: "USAMRDC",
    companyAliases: "USAMRDC; DHA R&D-MRDC; U.S. Army Medical Research and Development Command; formerly USAMRMC",
    parentAccount: "Defense Health Agency (DHA), U.S. Department of Defense (transition from U.S. Army completed in late 2024)",
    topIndustrySectorProfile: "Government \u2014 Military Medical Research & Development",
    secondaryIndustrySectorProfile: "Biotechnology / Life Sciences",
    description: "USAMRDC is the military's medical materiel developer, responsible for biomedical research, development, and acquisition in areas such as infectious diseases, combat casualty care, operational medicine, and chemical/biological defense. Headquartered at Fort Detrick, it oversees subordinate research laboratories and institutes worldwide and now operates under the Defense Health Agency.",
    website: "https://mrdc.health.mil (current domain; usamrdc.health.mil/mrdc.amedd.army.mil redirect here)",
    companyStructure: "U.S. federal government command (DoD/Defense Health Agency, with Army elements)",
    ownership: "Government",
    streetAddress: "810 Schreider Street, Fort Detrick",
    city: "Frederick",
    state: "MD",
    zipCode: "21702-5000",
    country: "USA",
    approximateEmployees: "Not disclosed (mix of military, federal civilian, and contractor personnel across worldwide subordinate commands)",
    approximateRevenue: "Not disclosed (annual budget not published as a single figure; funded through DoD/DHA appropriations)",
    keyProducts: "Military infectious disease research, combat casualty care solutions, operational medicine, medical chemical/biological defense, military medical materiel acquisition",
    researchBy: "Map research (Claude + SEC EDGAR)",
    dateOfResearch: "2026-06-12",
    resources: "https://mrdc.health.mil/index.cfm/about/headquarters; https://mrdc.health.mil/index.cfm/about/mission_vision",
    linkToReport: rpt("USAMRDC_UNC_Partner_Profile.pdf", "Xdltbv"),
  }),
];
