// Sample data for the homepage demo panel (components/workspace/DemoPanel.tsx).
// Bundled statically so the panel never makes a network call.
//
// PROVENANCE: every value below was captured from a REAL Pfizer company report
// generated by this app on 2026-08-08 (guest path, production build) and left
// unedited. Nothing here is invented. The capture is a snapshot, so the live
// figures will drift — re-run a Pfizer report and update this file if the panel
// starts to look stale.
//
// Note which sources a COMPANY report actually cites: SEC EDGAR (filings, XBRL)
// and OpenAlex. PubMed, ClinicalTrials.gov and NIH RePORTER feed the sector
// scans and partnership views, NOT this report type — so they are deliberately
// absent from the chips below.

// takes: nothing — static export
// does: describes the sample Pfizer brief the demo panel animates through
// returns: n/a (data module)
export const PFIZER_DEMO = {
  title: "PFIZER INC: Company Profile",
  // The report's own Executive Summary, verbatim.
  overview:
    "PFIZER INC reported revenue of $62.6B in FY2025 (−1.6% YoY). Net income was $7.8B in FY2025.",
  lines: [
    { text: "10-K filed February 25, 2026", chip: "SEC EDGAR" },
    { text: "Revenue $62.6B · R&D $10.4B · equity $86.8B", chip: "SEC XBRL" },
    { text: "22,847 works since 2024 reference this company", chip: "OpenAlex" },
    { text: "Key risks quoted from Item 1A", chip: "SEC 10-K" },
  ],
  // The three download buttons a real company report offers.
  formats: ["PDF", "Word", "Markdown"],
} as const;
