/** Curated sector list mirroring the backend's known sector seeds. */
export const SECTORS = [
  "Oncology",
  "Biotech",
  "Pharmaceutical",
  "Medtech",
  "Healthcare",
  "Health IT",
  "Rural Health",
  "Ag-Bio",
  "Technology",
  "Software",
  "Artificial Intelligence",
  "Semiconductors",
  "Cybersecurity",
  "Cloud Computing",
  "Fintech",
  "Quantum Computing",
  "Robotics",
  "Telecom",
  "Climate Tech",
  "Energy",
  "Automotive",
  "Aerospace",
  "Consumer",
  "Retail",
  "Finance",
  "Insurance",
  "Industrial",
];
